[[redirects]]
  from = "/sitemap.xml"
  to = "https://eecbrvehrhrvdzuutliq.supabase.co/functions/v1/generate-sitemap"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
